services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: sh -c "CHOKIDAR_USEPOLLING=true npm run dev"
    volumes:
      - ./server/src/:/app/src/

  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db

  client:
    build: ./client
    ports:
      - 8080:5173
    command: sh -c "CHOKIDAR_USEPOLLING=true npm run dev"
    volumes:
      - ./client/src/:/app/src/
